AllCops:
  Exclude:
    - config/software/cacerts.rb
    - config/software/openssl.rb
    - config/software/nodejs.rb
    - config/software/nokogiri.rb
    - bin/*
LineLength:
  Max: 250
HashSyntax:
  Enabled: False
FileName:
  Enabled: False
